"$schema" = 'https://starship.rs/config-schema.json'

palette='bioshock'

format = """
[](dark-green)\
$os\
$username\
[](bg:brown-sugar fg:dark-green)\
$directory\
[](fg:brown-sugar bg:brunswick-green)\
$git_branch\
$git_status\
[](fg:brunswick-green bg:midnight-green-light)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:midnight-green-light bg:midnight-green-dark)\
$docker_context\
[](fg:midnight-green-dark bg:rich-black)\
$time\
[ ](fg:rich-black)\
$line_break$character"""

# Palette definitions

[palettes.bioshock]
gunnmetal = "#192a26"
tiffany-blue = "#b0d7cd"
rich-black = "#031b18"
dark-green = "#05221e"
brunswick-green = "#194641"
dark-green-blue = "#062d2d"
brown-sugar = "#a66854"
midnight-green-light = "#0d4b4c"
gray-green = "#3d6360"
midnight-green-dark = "#0b3e3c"
dark-gray = "#697c7b"
light-gray = "#b2b2b2"
text = "#ffffff"
dark-text = "#000000"


[os]
disabled = false
style = "bg:dark-green fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:dark-green fg:text"
style_root = "bg:dark-green fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:dark-text bg:brown-sugar"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:brunswick-green"
format = '[[ $symbol $branch ](fg:tiffany-blue bg:brunswick-green)]($style)'

[git_status]
style = "bg:brunswick-green"
format = '[[($all_status$ahead_behind )](fg:tiffany-blue bg:brunswick-green)]($style)'

[nodejs]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[c]
symbol = " "
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[rust]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[golang]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[php]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[java]
symbol = " "
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[haskell]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[python]
symbol = ""
style = "bg:midnight-green-light"
format = '[[ $symbol( $version) ](fg:tiffany-blue bg:midnight-green-light)]($style)'

[docker_context]
symbol = ""
style = "bg:midnight-green-dark"
format = '[[ $symbol( $context) ](fg:tiffany-blue bg:midnight-green-dark)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:rich-black"
format = '[[  $time ](fg:tiffany-blue bg:rich-black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
